name: Update README Image Source

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    env:
      git_email: ${{ secrets.GIT_EMAIL }}
      git_name: ${{ secrets.GIT_NAME }}

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Set git config
      run: |
        git config --global user.email "${{ env.git_email }}"
        git config --global user.name "${{ env.git_name }}"

    - name: Wait and merge new commit
      run: |
        sleep 60
        git pull

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Update Image
      run: python update_img.py

    - name: Commit and push if changed
      run: |
        git diff --quiet || (git commit -am "Update image source" && git push)
      env:
        ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}